name: 'Image Assembly Line'
description: 'GitHub Action that runs our docker image build flow.'
author: 'freee K.K.'
inputs:
  image_name:
    require: true
  target:
    description: 'make target'
    default: 'build'
  no_push:
    description: 'set true if you do not want to push image to ECR'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
