name: 'Image Assembly Line'
description: 'GitHub Action that runs our docker image build flow.'
author: 'freee K.K.'
inputs:
  image_name:
    require: true
  target:
    description: 'make target'
    default: 'build'
  severity_level:
    description: 'severities of vulnerabilities to be displayed'
    default: 'CRITICAL' # Available values: UNKNOWN, LOW, MEDIUM, HIGH, CRITICAL
  scan_exit_code:
    description: 'Exit code when vulnerabilities were found'
    default: '0'
  no_push:
    description: 'set true if you do not want to push image to ECR'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
