name: "runner build-test"
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - test

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: create .env file
      run: |
        env > .env
    - name: run the make command
      run: |
        env
        echo "hi"
