name: "build-test"
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - master
      - develop
      - 'releases/*'
      - test
  pull_request:

jobs:
  build: # make sure build/ci work properly
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: '057575985710'
    - name: create .env file
      run: |
        env > .env
    - name: build image
      run: |
        make dev.build_image
    - name: run tests
      run: |
        make dev.all
