name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - develop
      - 'releases/*'
      - test

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      env:
        REGISTRY_NAME: '1234567890.dkr.ecr.ap-northeast-1.amazonaws.com' 
      with: 
        milliseconds: 1000
